# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(374, 228)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Logo/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        About.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=About)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Logo/logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=About)
        self.label_2.setGeometry(QtCore.QRect(110, 36, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=About)
        self.label_3.setGeometry(QtCore.QRect(120, 70, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=About)
        self.textBrowser.setGeometry(QtCore.QRect(10, 110, 351, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.b_OK = QtWidgets.QPushButton(parent=About)
        self.b_OK.setGeometry(QtCore.QRect(140, 190, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.b_OK.setFont(font)
        self.b_OK.setObjectName("b_OK")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label_2.setText(_translate("About", "RecoveryJpeg v1.7.0"))
        self.label_3.setText(_translate("About", "<html><head/><body><p><span style=\" font-weight:700;\">Author &amp; Developed by: </span><a href=\"https://www.facebook.com/QuangDaiVQD\"><span style=\" font-weight:700; text-decoration: underline; color:#0000ff;\">Vũ Quang Đại</span></a><br/></p></body></html>"))
        self.textBrowser.setHtml(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">RecoveryJpeg uses other tools such as JpegRepair, JpegRecovery, Irfan. The software was created for the purpose of restoring photos.</span></p></body></html>"))
        self.b_OK.setText(_translate("About", "OK"))
